module.exports = {
    NAVIGATION: 'NAVIGATION',
    GAME_CREATED: 'GAME_CREATED',
    GAME_UPDATED: 'GAME_UPDATED',
    REGISTER: 'REGISTER',
    LOGIN: 'LOGIN',
    TOKEN_REFRESH: 'TOKEN_REFRESH',
    GENERIC: 'GENERIC'
}
